### ISSUE TITLE
Autoscaling api

### ISSUE THREAD

**Issue by tweiss-mdm** [MaikuMori/helm-charts#15]
Hello,
When using the helm chart (5.2.0) with autoscaling enabled, the following errors is thrown:

`Error: INSTALLATION FAILED: unable to build kubernetes objects from release manifest: unable to recognize "": no matches for kind "HorizontalPodAutoscaler" in version "autoscaling/v2beta1"`

I suggest replaceing the api => `autoscaling/v2`

**Comment by MaikuMori** [comment]
I'm about to make a new release with `gotenberg 7.9.1`. I'll include the proposed fix.

I'll be honest, I haven't tested horizontal autoscaling much.

Eventually, I should either add conditionals based on K8S version or document supported versions. Currently, this tracks "recent" K8S versions because that's what I use in GKE.

**Comment by tweiss-mdm** [comment]
Nice, btw have you ever considered to test the charts ? 
I did use https://github.com/helm-unittest/helm-unittest a couple of times and liked it a lot

**Comment by MaikuMori** [comment]
I haven't used that, but I do have Helm install test on CI, it's just that it was using only testing against a single K8S version. I just updated it to use the last 5.

**Comment by MaikuMori** [comment]
It should be on [artifacthub.io](https://artifacthub.io/packages/helm/maikumori/gotenberg) in ~30 mins.
